<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kreyora.WebApi\Kreyora.WebApi.csproj" />
  </ItemGroup>

</Project>
